import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Image from 'next/image';
import SocialIcons from '../components/SocialIcons';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Alex Nielsen </h1>
        <div className="image-wrapper">
          <Image
            src="/images/me-wearing-hat.jpg"
            alt="Alex Nielsen wearing a baseball cap"
            width={200}
            height={200}
          />
        </div>
        <section className="skills {styles.skills}">
          <h3>TECHNICAL SKILLS</h3>
          <p>
            HTML, CSS, JavaScript, React, Next.js, Gatsby, Node/Express, MERN, REST APIs,
            Bootstrap, Git, Responsive Web Design, Photoshop{' '}
          </p>
          <h3>SOFT SKILLS</h3>
          <p>
            Eager to learn and develop new skills, Adaptable, Strong Work Ethic,
            Great Customer Service, Effective Communicator
          </p>

          <div>
            <p>
              I&apos;m a freelance web developer looking to make a move back
              into full-time. Ideally I&apos;d like to be working in
              music/entertainment or education (I spent a few years teaching
              music), but I would be very happy working anywhere that has a
              supportive team and that will allow me to continue learning and
              growing my skills.
            </p>
          </div>
          <SocialIcons />
        </section>
      </main>
      {console.log('Social Icons are from https://designmodo.com/')}
    </div>
  );
}
